### ISSUE TITLE
[BE] DB 환경 구축, 문자 스미싱 기능 개발

### ISSUE THREAD

**Issue by nayeong29** [GDSC-SWU/2024-VishingGuard-SolutionChallenge#1]
<h3>DB 환경 구축</h3>

- [x] 파일 구조 설정하기
- [x] firebase 연동하기
<h3>문자 스미싱 기능 개발</h3>

프론트에서 문자 내역 받아, 보이스 피싱 범죄 메세지인지 판별한 값 전달
- [x] 문자 스미싱 컨트롤러 구현
- [x] 문자 스미싱 서비스 구현
- [x] 문자 스미싱 컨트롤러 테스트 코드구현
- [x] 문자 스미싱 레포지토리 테스트 코드 구현

**Comment by nanna29** [comment]
Firebase DB 작업환경 구축 완료 & 문자 스미싱 코드 작업 완료

**Comment by nayeong29** [comment]
Firebase DB 작업환경 구축 완료 & 문자 스미싱 코드 작업 완료

**Comment by nayeong29** [comment]
Message Repository test code 작성 완료
